food = ['apple', 'banana', 'cocount'];
print(food);
print(food[0]);
food[0] = 'peach';
food[1] = 'pinapple';
food.append(True);
print(food);
food.extend('string');
print(food[4:]);
food.extend((['string', 2]));
print(food);
food.remove('s');
food.remove('t');
food.remove('r');
food.remove('i');
food.remove('n');
food.remove('g');
print(food);
print("cocount" in food);
print('cocount' not in food);
print(food[0:2:2]);
